SELECT 'ACCOUNTS' as table_name, COUNT(*) as row_count FROM SAAS_R.BRONZE.ACCOUNTS_RAW
UNION ALL
SELECT 'SUBSCRIPTIONS', COUNT(*) FROM SAAS_R.BRONZE.SUBSCRIPTIONS_RAW
UNION ALL
SELECT 'SUPPORT_TICKETS', COUNT(*) FROM SAAS_R.BRONZE.SUPPORT_TICKETS_RAW
UNION ALL
SELECT 'FEATURE_USAGE', COUNT(*) FROM SAAS_R.BRONZE.FEATURE_USAGE_RAW
UNION ALL
SELECT 'CHURN_EVENTS', COUNT(*) FROM SAAS_R.BRONZE.CHURN_EVENTS_RAW;

SELECT * FROM SAAS_R.BRONZE.ACCOUNTS_RAW LIMIT 3;
SELECT * FROM SAAS_R.BRONZE.SUBSCRIPTIONS_RAW LIMIT 3;
SELECT * FROM SAAS_R.BRONZE.SUPPORT_TICKETS_RAW LIMIT 3;
SELECT * FROM SAAS_R.BRONZE.FEATURE_USAGE_RAW LIMIT 3;
SELECT * FROM SAAS_R.BRONZE.CHURN_EVENTS_RAW LIMIT 3;