-- Create GOLD schema
CREATE SCHEMA IF NOT EXISTS SAAS_R.GOLD;

-- ANALYSIS 1: Churn Prediction Dataset
CREATE OR REPLACE VIEW SAAS_R.GOLD.CHURN_PREDICTION_FEATURES AS
SELECT 
    a.ACCOUNT_ID,
    a.INDUSTRY,
    a.COUNTRY,
    a.REFERRAL_SOURCE,
    a.SIGNUP_DATE,
    DATEDIFF(day, a.SIGNUP_DATE, CURRENT_DATE()) as ACCOUNT_AGE_DAYS,
    
    -- Subscription features
    s.PLAN_TIER,
    s.SEATS,
    s.MRR_AMOUNT,
    s.ARR_AMOUNT,
    s.BILLING_FREQUENCY,
    s.UPGRADE_FLAG,
    s.DOWNGRADE_FLAG,
    s.SUBSCRIPTION_DAYS,
    s.IS_ACTIVE,
    
    -- Support features
    COUNT(DISTINCT st.TICKET_ID) as TOTAL_TICKETS,
    AVG(st.RESOLUTION_TIME_HOURS) as AVG_RESOLUTION_TIME,
    AVG(st.FIRST_RESPONSE_TIME_MINUTES) as AVG_FIRST_RESPONSE_TIME,
    AVG(st.SATISFACTION_SCORE) as AVG_SATISFACTION_SCORE,
    SUM(CASE WHEN st.ESCALATION_FLAG THEN 1 ELSE 0 END) as ESCALATED_TICKETS,
    COUNT(DISTINCT CASE WHEN st.PRIORITY = 'urgent' THEN st.TICKET_ID END) as URGENT_TICKETS,
    
    -- Feature usage
    COUNT(DISTINCT fu.FEATURE_NAME) as UNIQUE_FEATURES_USED,
    SUM(fu.USAGE_COUNT) as TOTAL_USAGE_COUNT,
    SUM(fu.USAGE_DURATION_MINUTES) as TOTAL_USAGE_MINUTES,
    SUM(fu.ERROR_COUNT) as TOTAL_ERRORS,
    
    -- Target variable
    a.CHURN_FLAG as HAS_CHURNED
    
FROM SAAS_R.SILVER.ACCOUNTS a
LEFT JOIN SAAS_R.SILVER.SUBSCRIPTIONS s ON a.ACCOUNT_ID = s.ACCOUNT_ID
LEFT JOIN SAAS_R.SILVER.SUPPORT_TICKETS st ON a.ACCOUNT_ID = st.ACCOUNT_ID
LEFT JOIN SAAS_R.SILVER.FEATURE_USAGE fu ON s.SUBSCRIPTION_ID = fu.SUBSCRIPTION_ID
GROUP BY 
    a.ACCOUNT_ID, a.INDUSTRY, a.COUNTRY, a.REFERRAL_SOURCE, a.SIGNUP_DATE,
    s.PLAN_TIER, s.SEATS, s.MRR_AMOUNT, s.ARR_AMOUNT, s.BILLING_FREQUENCY,
    s.UPGRADE_FLAG, s.DOWNGRADE_FLAG, s.SUBSCRIPTION_DAYS, s.IS_ACTIVE, a.CHURN_FLAG;

-- ANALYSIS 2: Feature Adoption Tracking (Beta Features)
CREATE OR REPLACE VIEW SAAS_R.GOLD.BETA_FEATURE_ADOPTION AS
SELECT 
    fu.FEATURE_NAME,
    fu.USAGE_DATE,
    COUNT(DISTINCT fu.SUBSCRIPTION_ID) as ACTIVE_USERS,
    SUM(fu.USAGE_COUNT) as TOTAL_USAGE_COUNT,
    AVG(fu.USAGE_DURATION_MINUTES) as AVG_DURATION_MINUTES,
    SUM(fu.ERROR_COUNT) as TOTAL_ERRORS,
    ROUND(SUM(fu.ERROR_COUNT) * 100.0 / NULLIF(SUM(fu.USAGE_COUNT), 0), 2) as ERROR_RATE_PCT,
    
    -- Adoption by plan tier
    COUNT(DISTINCT CASE WHEN s.PLAN_TIER = 'Basic' THEN fu.SUBSCRIPTION_ID END) as BASIC_USERS,
    COUNT(DISTINCT CASE WHEN s.PLAN_TIER = 'Pro' THEN fu.SUBSCRIPTION_ID END) as PRO_USERS,
    COUNT(DISTINCT CASE WHEN s.PLAN_TIER = 'Enterprise' THEN fu.SUBSCRIPTION_ID END) as ENTERPRISE_USERS,
    
    -- Day-over-day growth
    LAG(COUNT(DISTINCT fu.SUBSCRIPTION_ID)) OVER (PARTITION BY fu.FEATURE_NAME ORDER BY fu.USAGE_DATE) as PREV_DAY_USERS,
    COUNT(DISTINCT fu.SUBSCRIPTION_ID) - LAG(COUNT(DISTINCT fu.SUBSCRIPTION_ID)) OVER (PARTITION BY fu.FEATURE_NAME ORDER BY fu.USAGE_DATE) as USER_GROWTH
    
FROM SAAS_R.SILVER.FEATURE_USAGE fu
JOIN SAAS_R.SILVER.SUBSCRIPTIONS s ON fu.SUBSCRIPTION_ID = s.SUBSCRIPTION_ID
WHERE fu.IS_BETA_FEATURE = TRUE
GROUP BY fu.FEATURE_NAME, fu.USAGE_DATE
ORDER BY fu.FEATURE_NAME, fu.USAGE_DATE;

-- ANALYSIS 3: Support Workload Forecasting
CREATE OR REPLACE VIEW SAAS_R.GOLD.SUPPORT_WORKLOAD_METRICS AS
SELECT 
    SUBMITTED_DATE,
    SUBMITTED_HOUR,
    SUBMITTED_DAY_OF_WEEK,
    CASE 
        WHEN SUBMITTED_DAY_OF_WEEK IN (1, 7) THEN 'Weekend'
        ELSE 'Weekday'
    END as DAY_TYPE,
    
    COUNT(TICKET_ID) as TICKET_COUNT,
    COUNT(CASE WHEN PRIORITY = 'urgent' THEN 1 END) as URGENT_COUNT,
    COUNT(CASE WHEN PRIORITY = 'high' THEN 1 END) as HIGH_COUNT,
    COUNT(CASE WHEN ESCALATION_FLAG THEN 1 END) as ESCALATED_COUNT,
    
    AVG(RESOLUTION_TIME_HOURS) as AVG_RESOLUTION_HOURS,
    AVG(FIRST_RESPONSE_TIME_MINUTES) as AVG_FIRST_RESPONSE_MINUTES,
    AVG(SATISFACTION_SCORE) as AVG_SATISFACTION,
    
    -- Rolling averages
    AVG(COUNT(TICKET_ID)) OVER (ORDER BY SUBMITTED_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) as ROLLING_7DAY_AVG_TICKETS,
    AVG(AVG(RESOLUTION_TIME_HOURS)) OVER (ORDER BY SUBMITTED_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) as ROLLING_7DAY_AVG_RESOLUTION
    
FROM SAAS_R.SILVER.SUPPORT_TICKETS
GROUP BY SUBMITTED_DATE, SUBMITTED_HOUR, SUBMITTED_DAY_OF_WEEK
ORDER BY SUBMITTED_DATE, SUBMITTED_HOUR;

-- ANALYSIS 4: Revenue Cohort Analysis by Referral Channel
CREATE OR REPLACE VIEW SAAS_R.GOLD.REVENUE_COHORT_ANALYSIS AS
SELECT 
    a.REFERRAL_SOURCE,
    DATE_TRUNC('month', a.SIGNUP_DATE) as COHORT_MONTH,
    DATE_TRUNC('month', s.START_DATE) as REVENUE_MONTH,
    DATEDIFF(month, DATE_TRUNC('month', a.SIGNUP_DATE), DATE_TRUNC('month', s.START_DATE)) as MONTHS_SINCE_SIGNUP,
    
    COUNT(DISTINCT a.ACCOUNT_ID) as ACCOUNTS_IN_COHORT,
    COUNT(DISTINCT s.SUBSCRIPTION_ID) as ACTIVE_SUBSCRIPTIONS,
    SUM(s.MRR_AMOUNT) as TOTAL_MRR,
    SUM(s.ARR_AMOUNT) as TOTAL_ARR,
    AVG(s.MRR_AMOUNT) as AVG_MRR_PER_ACCOUNT,
    
    -- Retention metrics
    COUNT(DISTINCT a.ACCOUNT_ID) * 100.0 / 
        FIRST_VALUE(COUNT(DISTINCT a.ACCOUNT_ID)) OVER (
            PARTITION BY a.REFERRAL_SOURCE, DATE_TRUNC('month', a.SIGNUP_DATE) 
            ORDER BY DATE_TRUNC('month', s.START_DATE)
        ) as RETENTION_RATE_PCT
    
FROM SAAS_R.SILVER.ACCOUNTS a
JOIN SAAS_R.SILVER.SUBSCRIPTIONS s ON a.ACCOUNT_ID = s.ACCOUNT_ID
GROUP BY a.REFERRAL_SOURCE, DATE_TRUNC('month', a.SIGNUP_DATE), DATE_TRUNC('month', s.START_DATE)
ORDER BY REFERRAL_SOURCE, COHORT_MONTH, REVENUE_MONTH;

-- ANALYSIS 5: Plan Tier Upgrade Funnel by Industry
CREATE OR REPLACE VIEW SAAS_R.GOLD.UPGRADE_FUNNEL_BY_INDUSTRY AS
SELECT 
    a.INDUSTRY,
    
    -- Funnel stages
    COUNT(DISTINCT a.ACCOUNT_ID) as TOTAL_ACCOUNTS,
    COUNT(DISTINCT CASE WHEN s.PLAN_TIER = 'Basic' AND s.IS_TRIAL = FALSE THEN a.ACCOUNT_ID END) as BASIC_PAID,
    COUNT(DISTINCT CASE WHEN s.UPGRADE_FLAG = TRUE THEN a.ACCOUNT_ID END) as ACCOUNTS_UPGRADED,
    COUNT(DISTINCT CASE WHEN s.PLAN_TIER = 'Pro' THEN a.ACCOUNT_ID END) as PRO_ACCOUNTS,
    COUNT(DISTINCT CASE WHEN s.PLAN_TIER = 'Enterprise' THEN a.ACCOUNT_ID END) as ENTERPRISE_ACCOUNTS,
    
    -- Conversion rates
    ROUND(COUNT(DISTINCT CASE WHEN s.PLAN_TIER = 'Basic' AND s.IS_TRIAL = FALSE THEN a.ACCOUNT_ID END) * 100.0 / 
          NULLIF(COUNT(DISTINCT a.ACCOUNT_ID), 0), 2) as TRIAL_TO_BASIC_PCT,
    ROUND(COUNT(DISTINCT CASE WHEN s.UPGRADE_FLAG = TRUE THEN a.ACCOUNT_ID END) * 100.0 / 
          NULLIF(COUNT(DISTINCT CASE WHEN s.PLAN_TIER = 'Basic' AND s.IS_TRIAL = FALSE THEN a.ACCOUNT_ID END), 0), 2) as BASIC_TO_UPGRADE_PCT,
    ROUND(COUNT(DISTINCT CASE WHEN s.PLAN_TIER = 'Pro' THEN a.ACCOUNT_ID END) * 100.0 / 
          NULLIF(COUNT(DISTINCT CASE WHEN s.UPGRADE_FLAG = TRUE THEN a.ACCOUNT_ID END), 0), 2) as UPGRADE_TO_PRO_PCT,
    ROUND(COUNT(DISTINCT CASE WHEN s.PLAN_TIER = 'Enterprise' THEN a.ACCOUNT_ID END) * 100.0 / 
          NULLIF(COUNT(DISTINCT CASE WHEN s.PLAN_TIER = 'Pro' THEN a.ACCOUNT_ID END), 0), 2) as PRO_TO_ENTERPRISE_PCT,
    
    -- Revenue metrics
    AVG(CASE WHEN s.PLAN_TIER = 'Basic' THEN s.MRR_AMOUNT END) as AVG_BASIC_MRR,
    AVG(CASE WHEN s.PLAN_TIER = 'Pro' THEN s.MRR_AMOUNT END) as AVG_PRO_MRR,
    AVG(CASE WHEN s.PLAN_TIER = 'Enterprise' THEN s.MRR_AMOUNT END) as AVG_ENTERPRISE_MRR,
    
    -- Time to upgrade
    AVG(CASE WHEN s.UPGRADE_FLAG = TRUE THEN s.SUBSCRIPTION_DAYS END) as AVG_DAYS_TO_UPGRADE
    
FROM SAAS_R.SILVER.ACCOUNTS a
LEFT JOIN SAAS_R.SILVER.SUBSCRIPTIONS s ON a.ACCOUNT_ID = s.ACCOUNT_ID
GROUP BY a.INDUSTRY
ORDER BY TOTAL_ACCOUNTS DESC;

-- ANALYSIS 6: Latency/Performance Analysis by Seat Count and Plan Tier
CREATE OR REPLACE VIEW SAAS_R.GOLD.PERFORMANCE_BY_TIER_SEATS AS
SELECT 
    s.PLAN_TIER,
    CASE 
        WHEN s.SEATS <= 5 THEN '1-5 seats'
        WHEN s.SEATS <= 20 THEN '6-20 seats'
        WHEN s.SEATS <= 50 THEN '21-50 seats'
        ELSE '50+ seats'
    END as SEAT_BUCKET,
    
    fu.FEATURE_NAME,
    
    COUNT(DISTINCT fu.SUBSCRIPTION_ID) as ACTIVE_SUBSCRIPTIONS,
    SUM(fu.USAGE_COUNT) as TOTAL_USAGE_COUNT,
    
    -- Performance metrics
    AVG(fu.USAGE_DURATION_SECS) as AVG_DURATION_SECS,
    PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY fu.USAGE_DURATION_SECS) as MEDIAN_DURATION_SECS,
    PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY fu.USAGE_DURATION_SECS) as P95_DURATION_SECS,
    PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY fu.USAGE_DURATION_SECS) as P99_DURATION_SECS,
    
    -- Error analysis
    SUM(fu.ERROR_COUNT) as TOTAL_ERRORS,
    ROUND(SUM(fu.ERROR_COUNT) * 100.0 / NULLIF(SUM(fu.USAGE_COUNT), 0), 2) as ERROR_RATE_PCT,
    
    -- Usage patterns
    AVG(fu.USAGE_COUNT) as AVG_USAGE_PER_SESSION,
    SUM(fu.USAGE_DURATION_MINUTES) / NULLIF(COUNT(DISTINCT fu.SUBSCRIPTION_ID), 0) as AVG_MINUTES_PER_SUBSCRIPTION
    
FROM SAAS_R.SILVER.FEATURE_USAGE fu
JOIN SAAS_R.SILVER.SUBSCRIPTIONS s ON fu.SUBSCRIPTION_ID = s.SUBSCRIPTION_ID
GROUP BY s.PLAN_TIER, SEAT_BUCKET, fu.FEATURE_NAME
ORDER BY s.PLAN_TIER, SEAT_BUCKET, fu.FEATURE_NAME;