-- File format for creating table structure (reads headers)
CREATE OR REPLACE FILE FORMAT SAAS_R.BRONZE.CSV_FF_INFER
    TYPE = CSV
    FIELD_DELIMITER = ','
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE = TRUE
    EMPTY_FIELD_AS_NULL = TRUE
    PARSE_HEADER = TRUE;

-- File format for loading data (skips headers)
CREATE OR REPLACE FILE FORMAT SAAS_R.BRONZE.CSV_FF_LOAD
    TYPE = CSV
    FIELD_DELIMITER = ','
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE = TRUE
    EMPTY_FIELD_AS_NULL = TRUE
    SKIP_HEADER = 1;

-- Create ACCOUNTS_RAW table
CREATE OR REPLACE TABLE SAAS_R.BRONZE.ACCOUNTS_RAW
USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
  FROM TABLE(
    INFER_SCHEMA(
      LOCATION => '@SAAS_R.BRONZE.KAGGLE_STAGE/ravenstack_accounts.csv.gz',
      FILE_FORMAT => 'SAAS_R.BRONZE.CSV_FF_INFER'
    )
  )
);

COPY INTO SAAS_R.BRONZE.ACCOUNTS_RAW
FROM '@SAAS_R.BRONZE.KAGGLE_STAGE/ravenstack_accounts.csv.gz'
FILE_FORMAT = (FORMAT_NAME = 'SAAS_R.BRONZE.CSV_FF_LOAD');

-- Create CHURN_EVENTS_RAW table
CREATE OR REPLACE TABLE SAAS_R.BRONZE.CHURN_EVENTS_RAW
USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
  FROM TABLE(
    INFER_SCHEMA(
      LOCATION => '@SAAS_R.BRONZE.KAGGLE_STAGE/ravenstack_churn_events.csv.gz',
      FILE_FORMAT => 'SAAS_R.BRONZE.CSV_FF_INFER'
    )
  )
);

COPY INTO SAAS_R.BRONZE.CHURN_EVENTS_RAW
FROM '@SAAS_R.BRONZE.KAGGLE_STAGE/ravenstack_churn_events.csv.gz'
FILE_FORMAT = (FORMAT_NAME = 'SAAS_R.BRONZE.CSV_FF_LOAD');

-- Create FEATURE_USAGE_RAW table
CREATE OR REPLACE TABLE SAAS_R.BRONZE.FEATURE_USAGE_RAW
USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
  FROM TABLE(
    INFER_SCHEMA(
      LOCATION => '@SAAS_R.BRONZE.KAGGLE_STAGE/ravenstack_feature_usage.csv.gz',
      FILE_FORMAT => 'SAAS_R.BRONZE.CSV_FF_INFER'
    )
  )
);

COPY INTO SAAS_R.BRONZE.FEATURE_USAGE_RAW
FROM '@SAAS_R.BRONZE.KAGGLE_STAGE/ravenstack_feature_usage.csv.gz'
FILE_FORMAT = (FORMAT_NAME = 'SAAS_R.BRONZE.CSV_FF_LOAD');

-- Create SUBSCRIPTIONS_RAW table
CREATE OR REPLACE TABLE SAAS_R.BRONZE.SUBSCRIPTIONS_RAW
USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
  FROM TABLE(
    INFER_SCHEMA(
      LOCATION => '@SAAS_R.BRONZE.KAGGLE_STAGE/ravenstack_subscriptions.csv.gz',
      FILE_FORMAT => 'SAAS_R.BRONZE.CSV_FF_INFER'
    )
  )
);

COPY INTO SAAS_R.BRONZE.SUBSCRIPTIONS_RAW
FROM '@SAAS_R.BRONZE.KAGGLE_STAGE/ravenstack_subscriptions.csv.gz'
FILE_FORMAT = (FORMAT_NAME = 'SAAS_R.BRONZE.CSV_FF_LOAD');

-- Create SUPPORT_TICKETS_RAW table
CREATE OR REPLACE TABLE SAAS_R.BRONZE.SUPPORT_TICKETS_RAW
USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
  FROM TABLE(
    INFER_SCHEMA(
      LOCATION => '@SAAS_R.BRONZE.KAGGLE_STAGE/ravenstack_support_tickets.csv.gz',
      FILE_FORMAT => 'SAAS_R.BRONZE.CSV_FF_INFER'
    )
  )
);

COPY INTO SAAS_R.BRONZE.SUPPORT_TICKETS_RAW
FROM '@SAAS_R.BRONZE.KAGGLE_STAGE/ravenstack_support_tickets.csv.gz'
FILE_FORMAT = (FORMAT_NAME = 'SAAS_R.BRONZE.CSV_FF_LOAD');

SELECT COUNT(*) FROM SAAS_R.BRONZE.ACCOUNTS_RAW;
SELECT COUNT(*) FROM SAAS_R.BRONZE.CHURN_EVENTS_RAW;
SELECT COUNT(*) FROM SAAS_R.BRONZE.FEATURE_USAGE_RAW;
SELECT COUNT(*) FROM SAAS_R.BRONZE.SUBSCRIPTIONS_RAW;
SELECT COUNT(*) FROM SAAS_R.BRONZE.SUPPORT_TICKETS_RAW;

-- Preview data
SELECT * FROM SAAS_R.BRONZE.ACCOUNTS_RAW LIMIT 50;
SELECT * FROM SAAS_R.BRONZE.CHURN_EVENTS_RAW LIMIT 10;
SELECT * FROM SAAS_R.BRONZE.FEATURE_USAGE_RAW LIMIT 10;
SELECT * FROM SAAS_R.BRONZE.SUBSCRIPTIONS_RAW LIMIT 10;
SELECT * FROM SAAS_R.BRONZE.SUPPORT_TICKETS_RAW LIMIT 10;


-- Check the actual data in the table
SELECT * FROM SAAS_R.BRONZE.CHURN_EVENTS_RAW LIMIT 10;

-- Check the row count
SELECT COUNT(*) FROM SAAS_R.BRONZE.CHURN_EVENTS_RAW;

-- Check the column names from the data
SELECT column_name, data_type 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE table_schema = 'BRONZE' 
  AND table_name = 'CHURN_EVENTS_RAW'
ORDER BY ordinal_position;