-- Top performing beta features
SELECT 
    FEATURE_NAME,
    SUM(ACTIVE_USERS) as TOTAL_USERS,
    ROUND(AVG(ERROR_RATE_PCT), 2) as AVG_ERROR_RATE,
    ROUND(AVG(AVG_DURATION_MINUTES), 2) as AVG_SESSION_MINUTES,
    SUM(BASIC_USERS) as TOTAL_BASIC_USERS,
    SUM(PRO_USERS) as TOTAL_PRO_USERS,
    SUM(ENTERPRISE_USERS) as TOTAL_ENTERPRISE_USERS
FROM SAAS_R.GOLD.BETA_FEATURE_ADOPTION
GROUP BY FEATURE_NAME
ORDER BY TOTAL_USERS DESC;

-- Beta feature adoption trend over time
SELECT 
    USAGE_DATE,
    FEATURE_NAME,
    ACTIVE_USERS,
    USER_GROWTH,
    ROUND(ERROR_RATE_PCT, 2) as ERROR_RATE_PCT
FROM SAAS_R.GOLD.BETA_FEATURE_ADOPTION
WHERE USAGE_DATE >= DATEADD(day, -30, CURRENT_DATE())
ORDER BY FEATURE_NAME, USAGE_DATE;

-- Features with highest error rates
SELECT 
    FEATURE_NAME,
    ROUND(AVG(ERROR_RATE_PCT), 2) as AVG_ERROR_RATE,
    SUM(TOTAL_ERRORS) as TOTAL_ERRORS,
    ROUND(AVG(ACTIVE_USERS), 2) as AVG_DAILY_USERS
FROM SAAS_R.GOLD.BETA_FEATURE_ADOPTION
GROUP BY FEATURE_NAME
HAVING AVG(ERROR_RATE_PCT) > 5
ORDER BY AVG_ERROR_RATE DESC;