-- Performance by plan tier and seat count
SELECT 
    PLAN_TIER,
    SEAT_BUCKET,
    FEATURE_NAME,
    ACTIVE_SUBSCRIPTIONS,
    ROUND(AVG_DURATION_SECS, 2) as AVG_DURATION_SECS,
    ROUND(MEDIAN_DURATION_SECS, 2) as MEDIAN_DURATION_SECS,
    ROUND(P95_DURATION_SECS, 2) as P95_DURATION_SECS,
    ROUND(P99_DURATION_SECS, 2) as P99_DURATION_SECS,
    ROUND(ERROR_RATE_PCT, 2) as ERROR_RATE_PCT
FROM SAAS_R.GOLD.PERFORMANCE_BY_TIER_SEATS
ORDER BY PLAN_TIER, SEAT_BUCKET, FEATURE_NAME;

-- Features with worst performance
SELECT 
    FEATURE_NAME,
    ROUND(AVG(P95_DURATION_SECS), 2) as AVG_P95_LATENCY,
    ROUND(AVG(ERROR_RATE_PCT), 2) as AVG_ERROR_RATE,
    SUM(ACTIVE_SUBSCRIPTIONS) as TOTAL_USERS
FROM SAAS_R.GOLD.PERFORMANCE_BY_TIER_SEATS
GROUP BY FEATURE_NAME
ORDER BY AVG_P95_LATENCY DESC
LIMIT 10;

-- Performance degradation by seat count
SELECT 
    SEAT_BUCKET,
    ROUND(AVG(AVG_DURATION_SECS), 2) as AVG_LATENCY,
    ROUND(AVG(P95_DURATION_SECS), 2) as P95_LATENCY,
    ROUND(AVG(ERROR_RATE_PCT), 2) as AVG_ERROR_RATE
FROM SAAS_R.GOLD.PERFORMANCE_BY_TIER_SEATS
GROUP BY SEAT_BUCKET
ORDER BY 
    CASE SEAT_BUCKET
        WHEN '1-5 seats' THEN 1
        WHEN '6-20 seats' THEN 2
        WHEN '21-50 seats' THEN 3
        WHEN '50+ seats' THEN 4
    END;