-- Cohort retention by referral source
SELECT 
    REFERRAL_SOURCE,
    COHORT_MONTH,
    MONTHS_SINCE_SIGNUP,
    ACCOUNTS_IN_COHORT,
    ROUND(TOTAL_MRR, 2) as TOTAL_MRR,
    ROUND(AVG_MRR_PER_ACCOUNT, 2) as AVG_MRR_PER_ACCOUNT,
    ROUND(RETENTION_RATE_PCT, 2) as RETENTION_RATE_PCT
FROM SAAS_R.GOLD.REVENUE_COHORT_ANALYSIS
WHERE MONTHS_SINCE_SIGNUP <= 12
ORDER BY REFERRAL_SOURCE, COHORT_MONTH, MONTHS_SINCE_SIGNUP;

-- Best performing referral channels
SELECT 
    REFERRAL_SOURCE,
    ROUND(AVG(CASE WHEN MONTHS_SINCE_SIGNUP = 0 THEN ACCOUNTS_IN_COHORT END), 2) as INITIAL_ACCOUNTS,
    ROUND(AVG(CASE WHEN MONTHS_SINCE_SIGNUP = 6 THEN RETENTION_RATE_PCT END), 2) as MONTH_6_RETENTION,
    ROUND(AVG(CASE WHEN MONTHS_SINCE_SIGNUP = 12 THEN RETENTION_RATE_PCT END), 2) as MONTH_12_RETENTION,
    ROUND(SUM(TOTAL_MRR), 2) as LIFETIME_MRR
FROM SAAS_R.GOLD.REVENUE_COHORT_ANALYSIS
GROUP BY REFERRAL_SOURCE
ORDER BY LIFETIME_MRR DESC;

-- Monthly cohort performance
SELECT 
    COHORT_MONTH,
    COUNT(DISTINCT REFERRAL_SOURCE) as REFERRAL_CHANNELS,
    SUM(ACCOUNTS_IN_COHORT) as TOTAL_NEW_ACCOUNTS,
    ROUND(AVG(AVG_MRR_PER_ACCOUNT), 2) as AVG_MRR,
    ROUND(AVG(CASE WHEN MONTHS_SINCE_SIGNUP = 3 THEN RETENTION_RATE_PCT END), 2) as MONTH_3_RETENTION
FROM SAAS_R.GOLD.REVENUE_COHORT_ANALYSIS
GROUP BY COHORT_MONTH
ORDER BY COHORT_MONTH DESC;