-- Industry upgrade performance
SELECT 
    INDUSTRY,
    TOTAL_ACCOUNTS,
    BASIC_PAID,
    PRO_ACCOUNTS,
    ENTERPRISE_ACCOUNTS,
    ROUND(TRIAL_TO_BASIC_PCT, 2) as TRIAL_TO_BASIC_PCT,
    ROUND(BASIC_TO_UPGRADE_PCT, 2) as BASIC_TO_UPGRADE_PCT,
    ROUND(UPGRADE_TO_PRO_PCT, 2) as UPGRADE_TO_PRO_PCT,
    ROUND(PRO_TO_ENTERPRISE_PCT, 2) as PRO_TO_ENTERPRISE_PCT,
    ROUND(AVG_DAYS_TO_UPGRADE, 2) as AVG_DAYS_TO_UPGRADE,
    ROUND(AVG_BASIC_MRR, 2) as AVG_BASIC_MRR,
    ROUND(AVG_PRO_MRR, 2) as AVG_PRO_MRR,
    ROUND(AVG_ENTERPRISE_MRR, 2) as AVG_ENTERPRISE_MRR
FROM SAAS_R.GOLD.UPGRADE_FUNNEL_BY_INDUSTRY
ORDER BY TOTAL_ACCOUNTS DESC;

-- Best converting industries
SELECT 
    INDUSTRY,
    TOTAL_ACCOUNTS,
    ROUND(BASIC_TO_UPGRADE_PCT, 2) as UPGRADE_RATE,
    ROUND(AVG_DAYS_TO_UPGRADE, 2) as AVG_DAYS_TO_UPGRADE,
    ROUND((AVG_PRO_MRR - AVG_BASIC_MRR), 2) as MRR_UPLIFT_TO_PRO,
    ROUND((AVG_ENTERPRISE_MRR - AVG_PRO_MRR), 2) as MRR_UPLIFT_TO_ENTERPRISE
FROM SAAS_R.GOLD.UPGRADE_FUNNEL_BY_INDUSTRY
WHERE BASIC_TO_UPGRADE_PCT IS NOT NULL
ORDER BY UPGRADE_RATE DESC
LIMIT 10;