-- Daily ticket volume and trends
SELECT 
    SUBMITTED_DATE,
    DAY_TYPE,
    TICKET_COUNT,
    URGENT_COUNT,
    ESCALATED_COUNT,
    ROUND(AVG_RESOLUTION_HOURS, 2) as AVG_RESOLUTION_HOURS,
    ROUND(AVG_SATISFACTION, 2) as AVG_SATISFACTION,
    ROUND(ROLLING_7DAY_AVG_TICKETS, 2) as ROLLING_7DAY_AVG_TICKETS
FROM SAAS_R.GOLD.SUPPORT_WORKLOAD_METRICS
WHERE SUBMITTED_DATE >= DATEADD(day, -30, CURRENT_DATE())
ORDER BY SUBMITTED_DATE DESC;

-- Peak hours analysis
SELECT 
    SUBMITTED_HOUR,
    ROUND(AVG(TICKET_COUNT), 2) as AVG_TICKETS,
    ROUND(AVG(URGENT_COUNT), 2) as AVG_URGENT,
    ROUND(AVG(AVG_RESOLUTION_HOURS), 2) as AVG_RESOLUTION_TIME
FROM SAAS_R.GOLD.SUPPORT_WORKLOAD_METRICS
GROUP BY SUBMITTED_HOUR
ORDER BY AVG_TICKETS DESC;

-- Weekend vs Weekday comparison
SELECT 
    DAY_TYPE,
    ROUND(AVG(TICKET_COUNT), 2) as AVG_TICKETS,
    ROUND(AVG(URGENT_COUNT), 2) as AVG_URGENT,
    ROUND(AVG(AVG_RESOLUTION_HOURS), 2) as AVG_RESOLUTION_HOURS,
    ROUND(AVG(AVG_SATISFACTION), 2) as AVG_SATISFACTION
FROM SAAS_R.GOLD.SUPPORT_WORKLOAD_METRICS
GROUP BY DAY_TYPE;